def fail(message):
    print("An error occured, terminating!")
    print("Error Message: " + message)
    exit(-1)
